Responsive Web Design
chukwuemeka1234/the-next-web-clone pull request #2
Opened 2021-04-07 18:32 UTC by chukwuemeka1234

This project is the clone of The Next Web

- HTML and CSS were used to build this project.
- Media query was used in CSS for the Mobile, Tablet, and Desktop versions for a Responsive Web Design

2021-04-07 20:21 UTC, elisha2kyakpo1 requested changes
**Hello guys, I'm so happy to see you reach this far, your project is really good**💪✔
Let's just fix few issues and move.
### required changes.

1. Fix the tablet breakpoint (Hint: you can use flex: 1 on the sub-content-container class)
**Highlights section**

1. Fix image problems(no image is displayed) see image.
![Highlights-missing-image](https://user-images.githubusercontent.com/53124548/113927155-6572d580-97ed-11eb-8bc2-a74adb795879.png)

2. The title should be a link (TNW).

**Latest funding**

1. The title should be a link
2. The nav menu (See more, Get updates, etc.) should be grouped in a nav tag, and each one should have a link (a tag)

**The header logo**
The logo should be a link.

**footer**
Increase the font for the logo in the footer, see from image;
![footer-logo](https://user-images.githubusercontent.com/53124548/113927978-7708ad00-97ee-11eb-8e4e-4dbba9cfc501.png)
**Remember** "As described in the Code reviews limit Policy you have 2 code reviews left for this project."

Make these changes and submit another review request.💪💪

Just in case you have a question, please reach me on slack by searching elisha kyakopo
Cheers🎉👈

2021-04-07 20:51 UTC, elisha2kyakpo1 commented
Hello guys, remember also to update your readme file, some info is missing, like your details. Happy coding

2021-04-07 22:03 UTC, chukwuemeka1234 commented
Thank you for the review.

On Wed, Apr 7, 2021, 9:51 PM Elisha Kyakopo ***@***.***>
wrote:

> Hello guys, remember also to update your readme file, some info is
> missing, like your details. Happy coding
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/chukwuemeka1234/the-next-web-clone/pull/2#issuecomment-815254407>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOYCLCBOXSWQQGIBKJB5TJDTHTAUPANCNFSM42RJX5ZQ>
> .
>

2021-04-08 11:30 UTC, Berabjesus requested changes
## Status: CHANGES REQUIRED :warning: :construction: 
#### Hi @mahbubul14  a very awesome start :+1:  Good job with what you have done so far. 👍 

#### However, you do have a few changes to carry out before we proceed so please take a look at the things you have to work on and their respective  _review comments_ below.

#### Mandatory comments

- [ ] As requested by the previous reviewer, The logo should be a link. That is the TNW logo should be a link on the mobile version too.
- [ ] Titles should be links. The title of each article is a header (`hx` tag) and has a link (`a` tag)
- [ ] Some details (screenshots) are not showing on your Readme. 

#### Optional comments

- [ ] remove everything in your .github folder except the workflows folder

- [ ] Some text (the date) in the `content-info` class is not showing properly. 

- [ ] The header on your mobile version needs to have a hamburger icon. Currently, on mobile width of `360 - 400 px` it doesn't show up.
- [ ] Footer link texts don't have proper formatting.

**Please have a look at the specific comments below**

#### ❗ You have one (1) remaining review left. As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. If you think that the code review was not fair, you can [request a second-opinion using this form.](https://airtable.com/shrmBIv6cXYrq4Fgv)**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-04-08 11:30 UTC, Berabjesus commented on README.md
> +<img src="./img/the-next-web-screen-shoot.JPG">
- [ ] As requested by the previous reviewer, some details, i.e the image on the readme, is not showing. Please fix that.

2021-04-08 11:30 UTC, Berabjesus commented on index.html
> +                <div class="logo-wrap"><img class="logo-image" src="img/tnw-logo.png" alt="logo-image"></div>
- [ ] make sure the logo has a link (`a` tag) on all version where its visible

2021-04-08 11:30 UTC, Berabjesus commented on index.html
> +                <h1>Opal cuts off your apps’ internet access to help you stop doomscrolling</h1>
- [ ] Titles should be links. The title of each article is a header (`hx` tag) and has a link (`a` tag)

2021-04-08 11:30 UTC, Berabjesus commented on index.html
> +                <span class="date">Tuesday - January 26, 2021</span>
- [ ] [Optional] This text is not fully visible. perhapse you could add some styling to it. Example `padding: 5px 0 0 
![image](https://user-images.githubusercontent.com/64360974/114018450-e8d80980-9875-11eb-891f-cb8f510ed9ac.png)

2021-04-08 11:30 UTC, Berabjesus commented on index.html
> +                    <a href="#"><i class="fas fa-bars"></i></a>
- [ ] [optional] The header on your mobile version needs to have a hamburger icon. Currently, on mobile width of `360 - 400 px` it doesn't show up.
### your page at 384 px 👇 
![image](https://user-images.githubusercontent.com/64360974/114018689-305e9580-9876-11eb-9343-20a4db9180f9.png)

### original website 👇 
![image](https://user-images.githubusercontent.com/64360974/114018895-6d2a8c80-9876-11eb-98fb-6db719af5b63.png)

2021-04-08 11:30 UTC, Berabjesus commented on index.html
> +            </div>
- [ ] [Optional] The highlighted items should have a proper text size
### your page👇 
![image](https://user-images.githubusercontent.com/64360974/114019110-b1b62800-9876-11eb-860c-824e8628868f.png)

### original page👇 

![image](https://user-images.githubusercontent.com/64360974/114019321-ef1ab580-9876-11eb-8d8d-4f8136e1b00e.png)

2021-04-08 16:15 UTC, chukwuemeka1234 commented
I need help pls. Bereket Beshane

2021-04-08 17:35 UTC, Berabjesus commented
> I need help pls. Bereket Beshane

How may i help you @chukwuemeka1234

2021-04-09 11:59 UTC, george-shammar approved these changes
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: 

**This milestone is approved** **Thank you for implementing the code review feedbacks from the previous reviewers. Good job**. :+1: :+1: :clap: :clap: 

**Congratulations**. :wine_glass: :wine_glass: 

**I like your website, it looks neat**. :clap: :clap: 


[OPTIONAL]

- [ ] **I strongly recommend that you clean up the .gtihub directory. You currently have asset directory nested in it with numerous image files.** 


**You can go ahead and merge this branch to the main branch.**

**Cheers and good luck with your next milestone.** :wine_glass: :wine_glass:

2021-04-09 12:52 UTC, merged